### ISSUE TITLE
getRecord() always defaults to the wrong signature

### ISSUE THREAD

**Issue by radicalappdev** [CoderlyStudio/FMProKit#6]
I'm running into an issue where Swift is always calling the wrong version of getRecord.

I'm trying to use this version:
```
 func getRecord<T: Codable>(table: String, id: String) async throws -> T { ... }
```

But Swift always seems to call this one, the one that expects an int:
```
 func getRecord<T: Codable>(table: String, id: Int) async throws -> T { ... }
```

The ID is defined as a string and I even tried casting it, but it is still happening.
`.getRecord(table: "Task", id: id as String)`

Now matter what I do I get this error:

`keyNotFound(CodingKeys(stringValue: "value", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"value\", intValue: nil) (\"value\").", underlyingError: nil))`

**Comment by franc-demarco** [comment]
Hello, @radicalappdev! Thank you for reporting the problem. This error is due to a change in the formatting of the FileMaker API response JSON. 

We have already fixed the issue and it will be available in the main branch shortly.
